# Generated by Django 4.0.6 on 2022-08-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_me_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
